apiVersion: apps/v1
kind: Deployment
metadata:
  name: hotstar-deployment
spec:
  replicas: 2 # Number of desired replicas
  selector:
    matchLabels:
      app: hotstar
  template:
    metadata:
      labels:
        app: hotstar
    spec:
      containers:
      - name: hotstar
        image: 891377235223.dkr.ecr.ap-south-1.amazonaws.com/syed:5891377235223.dkr.ecr.ap-south-1.amazonaws.com/syed:4891377235223.dkr.ecr.ap-south-1.amazonaws.com/syed:3
        ports:
        - containerPort: 3000  # Port your application listens on
